tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

ports:
  - port: 8000
    onOpen: open-preview
  - port: 8001
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
